version: 2
updates:
  - package-ecosystem: nuget
    directory: /webapp
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /crawler
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /crawler
      - /webapp/src/DoffinCaseman.Web
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
